apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "application.name" . }}-{{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client