apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.application.name }}-{{ .Values.subdirectories.reports }}-{{ .Release.Namespace }}"
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client