apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: "{{.Release.Namespace}}-{{.Chart.Name}}-pvc"
    labels:
        app: biot-wipo-validator
        cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-pvc"
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{Values.storage.size}}
  storageClassName: nfs-client