apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "biot-wipo-pvc"
    labels:
      app: biot-wipo
      cleanup: "biot-wipo-pvc"
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client