apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: biot-svs-ambasador
spec:
  prefix: /{{ .Release.Namespace }}/{{ include "application.fullname" . }}/
  rewrite: /
  timeout_ms: { { .Values.k8s.timeout_ms | int } }
  service: { { include "component.web.fullname" . } }.{{ .Release.Namespace }}
  add_request_headers:
    x-forwarded-prefix: /{{ .Release.Namespace }}/{{ include "application.fullname" . }}/