apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.application.name }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client