apiVersion: getambassador.io/v1
kind:  Mapping
metadata:
  name: {{ include "component.application.name" }}
spec:
  prefix: /{{ .Release.Namespace }}/{{ .Values.application.name }}-{{ .Values.instance }}/
  rewrite: /
  timeout_ms:  90000
  service: {{ .Release.Namespace }}/{{ .Values.application.name }}-{{ .Values.instance }}/
  add_request_headers:
    x-forwarded-prefix: /{{ .Release.Namespace }}/{{ .Values.application.name }}-{{ .Values.instance }}/