apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.name" . }}-{{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: "{{ .Values.application.name }}"
      component: "{{ .Values.component.biotWipo.name }}"
      instance: "{{ .Values.instance }}"
  replicas: {{ .Values.replicas.min }}
  template:
    metadata:
      {{- include "helper.labels" . | nindent 6 }}
    spec:
      containers:
        - name: {{ .Values.application.name }}
          image: {{ .Values.imageRegistry }}/{{ .Values.application.image }}:{{ .Values.application.version }}
          ports:
              - containerPort: 8080
          volumeMounts:
            - name: storage
              mountPath: helm/svs/templates
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Release.Namespace }}-{{ include "application.name" . }}
  livenessProbe:
    httpGet:
      path: /{{ .Release.Namespace }}/{{ .Values.application.name }}-{{ .Values.instance }}/
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 150
    periodSeconds: 15
    failureThreshold: 20
  readinessProbe:
     httpGet:
       path: /{{ .Release.Namespace }}/{{ .Values.application.name }}-{{ .Values.instance }}/actuator/health
       port: 8080
       scheme: HTTP
