apiVersion: getambassador.io/v1
kind:  Mapping
metadata:
  name: {{ include "application.name" . }}-{{ .Release.Namespace }}
spec:
  prefix: /{{ .Release.Namespace }}/{{ include "application.name" . }}-{{ .Release.Namespace }}/
  rewrite: ""
  timeout_ms:  90000
  service: {{ include "application.name" . }}-{{ .Release.Namespace }}