apiVersion: getambassador.io/v1
kind:  Mapping
metadata:
  name: biot-svs-ambasador
spec:
  prefix: {{ .Release.Namespace }}/{{ include "application.fullname" . }}/
  rewrite: /
  timeout_ms: 90000
  service: {{ include "application.fullname" . }}.{{ .Release.Namespace }}
  # Especially for OpenAPI 3.0 this is needed as it allows
  # to have a proper path in the generated API
  add_request_headers:
    x-forwarded-prefix: {{ .Release.Namespace }}/{{ include "application.fullname" . }}/