apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "application.name" . }} {{- include "helper.labels" . | nindent 2 }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client