apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "application.name" . }}.{{ .Release.Namespace }}2
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client