apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: biot-svs-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client