apiVersion: getambassador.io/v1
kind:  Mapping
metadata:
  name: svs-test
spec:
  prefix: /{{ .Release.Namespace }}/{{ .Values.application.name }}-{{ .Values.instance }}/
  rewrite: /
  timeout_ms: 90000
  service: {{ include "application.name" . }}.{{ .Release.Namespace }}:80
  add_request_headers:
    x-forwarded-prefix: /{{ .Release.Namespace }}/{{ .Values.application.name }}-{{ .Values.instance }}/