apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: {{ .Values.application.name }}
spec:
  prefix: /{{ .Release.Namespace }}-{{ .Values.application.name }}-{{ .Values.instance }}/
  rewrite: ""
  timeout_ms:  90000
  service: {{ .Values.application.name }}-{{ .Values.instance }}-{{ .Release.Namespace }}
  add_request_headers:
    x-forwarded-prefix: /{{ .Release.Namespace }}-{{ .Values.application.name }}-{{ .Values.instance }}/