apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "application.name" . }}-{{ .Release.Namespace }}
        {{- include "helper.labels" . | nindent 2 }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: nfs-client