application:
  name: svs
  component: jar
  image: svs-docker
  version: set-me-through-deploy-parameters
imageRegistry: containerhub.internal.epo.org:6666
instance: default
component:
  biotWipo:
    name: "service"
    image: "svs-docker"
    env: []
    requests:
      cpu: 2
      memory: 2Gi
    limits:
      cpu: 8
      memory: 8Gi
    storage: 8Gi

resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: '1'
    memory: "1024Mi"

replicas:
  dev: 1