application:
  name: svs
  image: svs-docker
  version: set-me-through-deploy-parameters
imageRegistry: containerhub.internal.epo.org:6666
instance: default
component:
  biotWipo:
    name: "service"
resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: '1'
    memory: "1024Mi"

replicas:
  min: 1